# Generated by Django 5.0.6 on 2024-09-05 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_maximo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('depende_de_sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N/A', 'No Aplica')], default='N/A', max_length=10)),
                ('depende_de_edad', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Variable de Estudio',
                'verbose_name_plural': 'Variables de Estudio',
            },
        ),
        migrations.CreateModel(
            name='EstudioSangre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_estudio', models.DateField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('atTG_IgA', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IgA anti Transglutaminasa')),
                ('aDGP_IgA', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IgA anti Gliadina Deaminada')),
                ('antiendomisio', models.CharField(blank=True, choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=10, null=True, verbose_name='Anticuerpos antiendomisio (EMA)')),
                ('hemoglobina', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('hematocrito', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ferritina', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hierro_serico', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vitamina_b12', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calcio_serico', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vitamina_d', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alt', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ALT (alanina aminotransferasa)')),
                ('ast', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='AST (aspartato aminotransferasa)')),
                ('colesterol_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('colesterol_hdl', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('trigliceridos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('glucemia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('celiac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='usuarios.celiac')),
            ],
            options={
                'verbose_name': 'Estudio de Sangre',
                'verbose_name_plural': 'Estudios de Sangre',
            },
        ),
    ]
