# Generated by Django 5.0.6 on 2024-09-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiosangre',
            name='celiac',
        ),
        migrations.DeleteModel(
            name='VariableEstudio',
        ),
        migrations.DeleteModel(
            name='EstudioSangre',
        ),
    ]
