# Generated by Django 5.0.6 on 2024-09-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTestVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('depends_on_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('N/A', 'No Aplica')], default='N/A', max_length=10)),
                ('depends_on_age', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Variable de Estudio',
                'verbose_name_plural': 'Variables de Estudio',
            },
        ),
        migrations.DeleteModel(
            name='VariableEstudio',
        ),
        migrations.AddField(
            model_name='bloodtest',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
