# Generated by Django 5.0.6 on 2024-09-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0004_bloodtestvariables_delete_variableestudio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodtest',
            name='description',
        ),
        migrations.AddField(
            model_name='bloodtestvariables',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
