# Generated by Django 5.0.6 on 2024-09-26 19:57

import sqlalchemy.sql._elements_constructors
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0008_referencevalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='lab',
            field=models.CharField(default=sqlalchemy.sql._elements_constructors.null, max_length=150, null=True),
        ),
    ]
