# Generated by Django 5.0.6 on 2024-09-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0010_bloodtest_adgp_igg_bloodtest_colesterol_ldl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='aDGP_IgA',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='IgA anti Gliadina Deaminada'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='aDGP_IgG',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='IgG anti Gliadina Deaminada'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='atTG_IgA',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='IgA anti Transglutaminasa'),
        ),
    ]
