# Generated by Django 5.0.6 on 2024-09-28 02:21

import sqlalchemy.sql._elements_constructors
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0011_alter_bloodtest_adgp_iga_alter_bloodtest_adgp_igg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencevalues',
            name='max_value',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='referencevalues',
            name='min_value',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='referencevalues',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=sqlalchemy.sql._elements_constructors.null, max_length=10, null=True),
        ),
    ]
