# Generated by Django 5.0.6 on 2024-09-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0012_alter_referencevalues_max_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencevalues',
            name='max_value',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
