# Generated by Django 5.0.6 on 2024-09-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0013_alter_referencevalues_max_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='GluttyTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=400)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
