# Generated by Django 5.0.6 on 2024-10-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0015_delete_bloodtestvariables_gluttytips_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='unit_of_measurement',
            field=models.CharField(default='hola', max_length=50, null=True),
        ),
    ]
