# Generated by Django 5.0.6 on 2024-10-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0016_variable_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodtest',
            options={'ordering': ['-registration_date'], 'verbose_name': 'Estudio de Sangre', 'verbose_name_plural': 'Estudios de Sangre'},
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='aDGP_IgA',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='IgA anti Gliadina Deaminada'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='aDGP_IgG',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='IgG anti Gliadina Deaminada'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='atTG_IgA',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='IgA anti Transglutaminasa'),
        ),
    ]
