# Generated by Django 5.0.6 on 2024-10-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0017_alter_bloodtest_options_alter_bloodtest_adgp_iga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='aDGP_IgA',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='IgA anti Gliadina Deaminada'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='aDGP_IgG',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='IgG anti Gliadina Deaminada'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='antiendomisio',
            field=models.CharField(blank=True, choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=8, null=True, verbose_name='Anticuerpos antiendomisio (EMA)'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='atTG_IgA',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='IgA anti Transglutaminasa'),
        ),
    ]
