# Generated by Django 5.0.6 on 2024-10-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0018_alter_bloodtest_adgp_iga_alter_bloodtest_adgp_igg_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodtest',
            options={'ordering': ['-test_date'], 'verbose_name': 'Estudio de Sangre', 'verbose_name_plural': 'Estudios de Sangre'},
        ),
    ]
