# Generated by Django 5.0.6 on 2024-10-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0019_alter_bloodtest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='public_id',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
