# Generated by Django 5.0.6 on 2024-10-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0020_alter_bloodtest_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='aDGP_IgA',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='IgA anti Gliadina Deaminada'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='aDGP_IgG',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='IgG anti Gliadina Deaminada'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='alt',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True, verbose_name='ALT (alanina aminotransferasa)'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='antiendomisio',
            field=models.CharField(blank=True, choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], default=None, max_length=8, null=True, verbose_name='Anticuerpos antiendomisio (EMA)'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='ast',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True, verbose_name='AST (aspartato aminotransferasa)'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='atTG_IgA',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='IgA anti Transglutaminasa'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='calcio_serico',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='colesterol_hdl',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='colesterol_ldl',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='colesterol_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='ferritina',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='glucemia',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='hematocrito',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='hemoglobina',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='hierro_serico',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='trigliceridos',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='vitamina_b12',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='vitamina_d',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
