# Generated by Django 5.0.6 on 2024-11-12 16:38

import secured_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0022_alter_bloodtest_hemoglobina_alter_bloodtest_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='aDGP_IgA',
            field=secured_fields.fields.EncryptedCharField(blank=True, default=None, max_length=8, null=True, verbose_name='IgA anti Gliadina Deaminada'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='aDGP_IgG',
            field=secured_fields.fields.EncryptedCharField(blank=True, default=None, max_length=8, null=True, verbose_name='IgG anti Gliadina Deaminada'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='alt',
            field=secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True, verbose_name='ALT (alanina aminotransferasa)'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='antiendomisio',
            field=secured_fields.fields.EncryptedCharField(blank=True, choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], default=None, max_length=8, null=True, verbose_name='Anticuerpos antiendomisio (EMA)'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='ast',
            field=secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True, verbose_name='AST (aspartato aminotransferasa)'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='atTG_IgA',
            field=secured_fields.fields.EncryptedCharField(blank=True, default=None, max_length=8, null=True, verbose_name='IgA anti Transglutaminasa'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='calcio_serico',
            field=secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='colesterol_hdl',
            field=secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='colesterol_ldl',
            field=secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='colesterol_total',
            field=secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='ferritina',
            field=secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='glucemia',
            field=secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='hematocrito',
            field=secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='hierro_serico',
            field=secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='public_id',
            field=secured_fields.fields.EncryptedCharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='test_date',
            field=secured_fields.fields.EncryptedDateField(searchable=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='trigliceridos',
            field=secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='url',
            field=secured_fields.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='vitamina_b12',
            field=secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='vitamina_d',
            field=secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
