# Generated by Django 5.0.6 on 2024-11-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0023_alter_bloodtest_adgp_iga_alter_bloodtest_adgp_igg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='test_date',
            field=models.DateField(),
        ),
    ]
