# Generated by Django 5.0.6 on 2024-10-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chat_history_id',
            field=models.CharField(default='Id Default'),
        ),
    ]
