# Generated by Django 5.0.6 on 2024-08-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0003_alter_branch_number_alter_commerce_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commerce',
            name='social_reason',
        ),
    ]
