# Generated by Django 5.0.6 on 2024-08-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0005_remove_branch_number_branch_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
