# Generated by Django 5.0.6 on 2024-08-08 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0006_delete_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(default=None, max_length=10)),
                ('optional_phone', models.CharField(blank=True, max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('separated_kitchen', models.BooleanField(default=False)),
                ('just_takeaway', models.BooleanField(default=False)),
                ('commerce', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='comercios.commerce')),
            ],
        ),
    ]
