# Generated by Django 5.0.6 on 2024-08-12 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0007_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='commerce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='comercios.commerce'),
        ),
    ]
