# Generated by Django 5.0.6 on 2024-08-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0008_alter_branch_commerce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='branch',
            name='optional_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
