# Generated by Django 5.0.6 on 2024-08-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0009_alter_branch_name_alter_branch_optional_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='separated_kitchen',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
