# Generated by Django 5.0.6 on 2024-08-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0010_alter_branch_separated_kitchen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='separated_kitchen',
            field=models.BooleanField(default=False),
        ),
    ]
