# Generated by Django 5.0.6 on 2024-08-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0011_alter_branch_separated_kitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerce',
            name='menu_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commerce',
            name='menu_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
