# Generated by Django 5.0.6 on 2024-08-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0013_remove_commerce_menu_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
