# Generated by Django 5.0.6 on 2024-08-15 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0014_branch_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_url', models.URLField(blank=True, max_length=500, null=True)),
                ('commerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='comercios.commerce')),
            ],
        ),
    ]
