# Generated by Django 5.0.6 on 2024-08-19 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0016_remove_branch_location_remove_commerce_menu_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='comercios.branch'),
        ),
    ]
