# Generated by Django 5.0.6 on 2024-08-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0017_alter_location_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='public_id',
            field=models.CharField(default='', max_length=300),
        ),
    ]
