# Generated by Django 5.0.6 on 2024-08-26 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0018_menu_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('public_id', models.CharField(default='', max_length=300)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='comercios.branch')),
            ],
        ),
    ]
