# Generated by Django 5.0.6 on 2024-08-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0019_picturebranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='optional_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
