# Generated by Django 5.0.6 on 2024-08-31 23:45

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0021_commerce_search_vector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commerce',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='comercios_c_search__36f917_gin'),
        ),
    ]
