# Generated by Django 5.0.6 on 2024-12-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0025_schedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
    ]
