# Generated by Django 5.0.6 on 2024-06-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_rnpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='denominacion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
