# Generated by Django 5.0.6 on 2024-07-02 22:35

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_denominacion_alter_producto_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoSearchView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('denominacion', models.CharField(max_length=500)),
                ('rnpa', models.CharField(max_length=255)),
                ('marca_nombre', models.CharField(max_length=255)),
                ('tipo_nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'producto_search_view',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='productos_p_search__06d087_gin'),
        ),
    ]
