# Generated by Django 5.0.6 on 2024-07-03 14:07

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_productosearchview_producto_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
