# Generated by Django 5.0.6 on 2024-07-03 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_productosearchview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoSearchView',
        ),
    ]
