# Generated by Django 5.0.6 on 2024-07-04 23:15

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_delete_productosearchview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_en', models.CharField(max_length=255, verbose_name='Product Name (English)')),
                ('product_name_es', models.CharField(max_length=255, verbose_name='Product Name (Spanish)')),
                ('generic_name', models.CharField(max_length=255, verbose_name='Generic Name')),
                ('quantity', models.CharField(max_length=50, verbose_name='Quantity')),
                ('serving_size', models.CharField(max_length=50, verbose_name='Serving Size')),
                ('brands', models.CharField(max_length=255, verbose_name='Brands')),
                ('categories', models.CharField(max_length=255, verbose_name='Categories')),
                ('emb_codes', models.CharField(max_length=255, verbose_name='Emb Codes')),
                ('allergens', models.CharField(max_length=255, verbose_name='Allergens')),
                ('ean', models.CharField(max_length=255, verbose_name='EAN')),
                ('searchvector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Productos con Barcode',
            },
        ),
    ]
