# Generated by Django 5.0.6 on 2024-07-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_productobarcode_allergens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productobarcode',
            name='product_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Name (English)'),
        ),
        migrations.AlterField(
            model_name='productobarcode',
            name='product_name_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Name (Spanish)'),
        ),
    ]
