# Generated by Django 5.0.6 on 2024-07-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_alter_productobarcode_allergens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productobarcode',
            name='allergens',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Allergens'),
        ),
        migrations.AlterField(
            model_name='productobarcode',
            name='brands',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Brands'),
        ),
        migrations.AlterField(
            model_name='productobarcode',
            name='categories',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='productobarcode',
            name='emb_codes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Emb Codes'),
        ),
        migrations.AlterField(
            model_name='productobarcode',
            name='generic_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Generic Name'),
        ),
        migrations.AlterField(
            model_name='productobarcode',
            name='product_name_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Product Name (English)'),
        ),
        migrations.AlterField(
            model_name='productobarcode',
            name='product_name_es',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Product Name (Spanish)'),
        ),
        migrations.AlterField(
            model_name='productobarcode',
            name='quantity',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='productobarcode',
            name='serving_size',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Serving Size'),
        ),
    ]
