# Generated by Django 5.0.6 on 2024-07-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_alter_productobarcode_allergens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productobarcode',
            name='rnpa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
