# Generated by Django 5.0.6 on 2024-10-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0002_label_labelxpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='likes_number',
        ),
        migrations.AddField(
            model_name='post',
            name='comments_number',
            field=models.IntegerField(default=0),
        ),
    ]
