# Generated by Django 5.0.6 on 2024-12-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0006_favorite_created_at_like_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
