# Generated by Django 5.0.6 on 2024-12-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0007_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
