# Generated by Django 5.0.6 on 2024-06-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_datebirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dateBirth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='gender',
            field=models.CharField(choices=[('MALE', 'M'), ('FEMALE', 'F'), ('OTHER', 'O')], default='MALE', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
