# Generated by Django 5.0.6 on 2024-09-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='celiac',
            name='show_message',
            field=models.BooleanField(default=True),
        ),
    ]
