# Generated by Django 5.0.6 on 2024-10-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_celiac_show_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='celiac',
            name='next_analysis_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
