# Generated by Django 5.0.6 on 2024-12-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_celiac_next_analysis_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_changing_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
